services:
  postgres:
    image: postgres:16
    container_name: biblioteca-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  biblioteca-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/biblioteca
    depends_on:
      - postgres
    volumes:
      - ./biblioteca_api:/app/biblioteca_api
      - ./run.py:/app/run.py
      - ./db.py:/app/db.py

volumes:
  postgres-data:
