-- Script de inicialização do banco de dados da biblioteca
-- Este script cria as tabelas se elas não existirem

-- 1. Tabela ALUNO
CREATE TABLE IF NOT EXISTS ALUNO (
    MAT_ALUNO        SERIAL    PRIMARY KEY,
    NOME       VARCHAR(100)   NOT NULL,
    EMAIL      VARCHAR(100),
    CURSO      VARCHAR(100)
);

-- 2. Tabela LIVRO
CREATE TABLE IF NOT EXISTS LIVRO (
    COD        SERIAL         PRIMARY KEY,
    TITULO     VARCHAR(200)   NOT NULL,
    AUTOR      VARCHAR(100),
    EDITORA    VARCHAR(100),
    ANO        INTEGER
);

-- 3. Tabela EXEMPLAR
CREATE TABLE IF NOT EXISTS EXEMPLAR (
    TOMBO      SERIAL         PRIMARY KEY,
    COD_LIVRO  INTEGER        NOT NULL,
    FOREIGN KEY (COD_LIVRO)
        REFERENCES LIVRO(COD)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- 4. Tabela EMPRESTIMO
CREATE TABLE IF NOT EXISTS EMPRESTIMO (
    COD              SERIAL         PRIMARY KEY,
    MAT_ALUNO        INTEGER    NOT NULL,
    DATA_EMPRESTIMO  DATE           NOT NULL,
    DATA_PREVISTA_DEV DATE          NOT NULL,
    DATA_DEVOLUCAO   DATE,
    DATA_ATRASO      DATE,
    FOREIGN KEY (MAT_ALUNO)
        REFERENCES ALUNO(MAT_ALUNO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- 5. Tabela EMP_EXEMPLAR (relação N:N entre EMPRESTIMO e EXEMPLAR)
CREATE TABLE IF NOT EXISTS EMP_EXEMPLAR (
    COD_EMPRESTIMO   INTEGER        NOT NULL,
    TOMBO_EXEMPLAR   INTEGER        NOT NULL,
    PRIMARY KEY (COD_EMPRESTIMO, TOMBO_EXEMPLAR),
    FOREIGN KEY (COD_EMPRESTIMO)
        REFERENCES EMPRESTIMO(COD)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (TOMBO_EXEMPLAR)
        REFERENCES EXEMPLAR(TOMBO)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
